project:
  type: website
  output-dir: docs
  
website:
  title: "Benjamin Ramsey's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/beramsey47
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

